---

- hosts: all
  become: true
  tasks:
  #Ubuntu
  - name: install apache2 package and php
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

 #CentOS  
  - name: install httpd package and php
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"


